using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using High10.CustomControls;
using High10.Droid.Renderers;
using Xamarin.Forms.Platform.Android;

[assembly: Xamarin.Forms.ExportRendererAttribute( typeof( LongPressListView ), typeof( LongPressListViewRenderer ) )]
namespace High10.Droid.Renderers {
  public class LongPressListViewRenderer : ListViewRenderer {
    protected override void OnElementChanged( ElementChangedEventArgs<Xamarin.Forms.ListView> e ) {
      base.OnElementChanged( e );

      if ( Control == null ) {
        SetNativeControl( new Android.Widget.ListView( Context ) );
      }

      Control.ItemLongClick += OnLongClick;

    }

    private void OnLongClick( object sender, AdapterView.ItemLongClickEventArgs e ) {
      var element = Element as LongPressListView;
      element?.HandleItemLongPressed( e.Position - 1 ); // Autogenerated headerview is position 0
    }
  }
}